storage_target: local-lvm
domain: example.com
network_bridge: vmbr4
vm_id_start: 10001
node_cidr: 192.168.10.0/24
pod_cidr: 10.0.0.0/16
service_cidr: 172.16.0.0/20
master:
  nodes: 3
  cores: 4 # number of cores
  memory: 4096  # memory in MB
  storage: 50 # storage in GB
worker:
  nodes: 4
  cores: 4
  memory: 4096
  storage: 50