network:
  domain: example.com
  node_cidr: 192.168.10.0/24
  pod_cidr: 10.0.0.0/16
  service_cidr: 172.16.0.0/20
proxmox:
  storage_target: local-lvm
  network_bridge: vmbr4
  password: "1234"
  vm_template_id: 10000
  vm_id_start: 10001
master:
  nodes: 3
  cores: 4 # number of cores
  memory: 4096  # memory in MB
  storage: 50 # storage in GB
worker:
  nodes: 4
  cores: 4
  memory: 4096
  storage: 50
auth:
  password: '1234'