- name: Create Cloud Image Template with Ubuntu 22.04
  hosts: proxmox-hosts
  tasks:
    - name: Download Ubuntu 22.04 Cloud Image
      shell: "wget -O /tmp/ubuntu-22.04.img $image_url"
    
    - name: Resize Ubuntu 22.04 Cloud Image
      shell: qemu-img resize /tmp/ubuntu-22.04.img 64G

    - name: Create Template VM
      shell: >
        qm create $template_id \
        --ostype "l26" \
        --name $template_hn \
        --description "Ubuntu 22.04 Cloud Image" \
        --agent 1 \
        --cpu cputype=host \
        --cores 1 \
        --memory 1024 \
        --net0 "virtio,bridge={{template_bridge}},firewall=1" \
        --scsihw virtio-scsi-single \
        --boot order=ide0,scsi0,net0 \
        --ide1 local-lvm:cloudinit \
        --ipconfig0 "ip=dhcp" \
        --cipassword "$template_password" \
        --template true
  
    - name: Upload Ubuntu 22.04 Cloud Image to Proxmox
      shell: qm disk import $template_id /tmp/ubuntu-22.04.img $storage_target

    - name: Discard Ubuntu 22.04 Drive
      shell: qm set $template_id --ide0 "$storage_target:vm-$template_id-disk-0,discard=on"

    # - name: Clone Ubuntu 22.04 Cloud Image
    #   shell: qm clone $item.vm_id $item.vm_id-clone --name $item.hn-clone --full true